#ifndef SRC_IDE_NODE_ENGINE_VERSION_H_
#define SRC_IDE_NODE_ENGINE_VERSION_H_

#include "node_version.h"

#define IDE_NODE_ENGINE_MAJOR_VERSION 1
#define IDE_NODE_ENGINE_MINOR_VERSION 0
#define IDE_NODE_ENGINE_PATCH_VERSION 0

#define IDE_NODE_ENGINE_VERSION_STRING  NODE_STRINGIFY(IDE_NODE_ENGINE_MAJOR_VERSION) "." \
                               NODE_STRINGIFY(IDE_NODE_ENGINE_MINOR_VERSION) "." \
                               NODE_STRINGIFY(IDE_NODE_ENGINE_PATCH_VERSION)

#endif  // SRC_IDE_NODE_ENGINE_VERSION_H_